// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoSara.Data;

#nullable disable

namespace ProjetoSARA.NET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SEQ_ALERTA");

            modelBuilder.HasSequence("SEQ_LEITURA_SENSOR");

            modelBuilder.HasSequence("SEQ_LOCALIZACAO");

            modelBuilder.HasSequence("SEQ_NIVEL_ALERTA");

            modelBuilder.HasSequence("SEQ_NOTIFICACAO");

            modelBuilder.HasSequence("SEQ_SENSOR");

            modelBuilder.HasSequence("SEQ_STATUS_NOTIFICACAO");

            modelBuilder.HasSequence("SEQ_TIPO_SENSOR");

            modelBuilder.HasSequence("SEQ_TIPO_USUARIO");

            modelBuilder.HasSequence("SEQ_USUARIO");

            modelBuilder.Entity("ProjetoSara.Models.Alerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<long?>("LocalizacaoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LOCALIZACAO_ID");

                    b.Property<string>("Mensagem")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MENSAGEM");

                    b.Property<long?>("NivelAlertaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NIVEL_ALERTA_ID");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("LocalizacaoId");

                    b.HasIndex("NivelAlertaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ALERTA");
                });

            modelBuilder.Entity("ProjetoSara.Models.LeituraSensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<long?>("SensorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SENSOR_ID");

                    b.Property<string>("Unidade")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UNIDADE");

                    b.Property<double?>("Valor")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("LEITURASENSOR");
                });

            modelBuilder.Entity("ProjetoSara.Models.Localizacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LOCALIZACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cidade")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Estado")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ESTADO");

                    b.HasKey("Id");

                    b.ToTable("LOCALIZACAO");
                });

            modelBuilder.Entity("ProjetoSara.Models.NivelAlerta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_NIVEL_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("NIVELALERTA");
                });

            modelBuilder.Entity("ProjetoSara.Models.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_NOTIFICACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlertaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ALERTA_ID");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ENVIO");

                    b.Property<long?>("StatusId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("STATUS_ID");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("NOTIFICACAO");
                });

            modelBuilder.Entity("ProjetoSara.Models.Sensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("LocalizacaoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LOCALIZACAO_ID");

                    b.Property<long?>("TipoSensorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TIPO_SENSOR_ID");

                    b.HasKey("Id");

                    b.HasIndex("LocalizacaoId");

                    b.HasIndex("TipoSensorId");

                    b.ToTable("SENSOR");
                });

            modelBuilder.Entity("ProjetoSara.Models.StatusNotificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_STATUS_NOTIFICACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("STATUSNOTIFICACAO");
                });

            modelBuilder.Entity("ProjetoSara.Models.TipoSensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TIPO_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("TIPOSENSOR");
                });

            modelBuilder.Entity("ProjetoSara.Models.TipoUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TIPO_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("TIPOUSUARIO");
                });

            modelBuilder.Entity("ProjetoSara.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA");

                    b.Property<long?>("TipoUsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TIPO_USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("ProjetoSara.Models.Alerta", b =>
                {
                    b.HasOne("ProjetoSara.Models.Localizacao", "Localizacao")
                        .WithMany("Alertas")
                        .HasForeignKey("LocalizacaoId");

                    b.HasOne("ProjetoSara.Models.NivelAlerta", "NivelAlerta")
                        .WithMany("Alertas")
                        .HasForeignKey("NivelAlertaId");

                    b.HasOne("ProjetoSara.Models.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Localizacao");

                    b.Navigation("NivelAlerta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoSara.Models.LeituraSensor", b =>
                {
                    b.HasOne("ProjetoSara.Models.Sensor", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("SensorId");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("ProjetoSara.Models.Notificacao", b =>
                {
                    b.HasOne("ProjetoSara.Models.Alerta", "Alerta")
                        .WithMany()
                        .HasForeignKey("AlertaId");

                    b.HasOne("ProjetoSara.Models.StatusNotificacao", "Status")
                        .WithMany("Notificacoes")
                        .HasForeignKey("StatusId");

                    b.HasOne("ProjetoSara.Models.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Alerta");

                    b.Navigation("Status");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoSara.Models.Sensor", b =>
                {
                    b.HasOne("ProjetoSara.Models.Localizacao", "Localizacao")
                        .WithMany("Sensores")
                        .HasForeignKey("LocalizacaoId");

                    b.HasOne("ProjetoSara.Models.TipoSensor", "TipoSensor")
                        .WithMany("Sensores")
                        .HasForeignKey("TipoSensorId");

                    b.Navigation("Localizacao");

                    b.Navigation("TipoSensor");
                });

            modelBuilder.Entity("ProjetoSara.Models.Usuario", b =>
                {
                    b.HasOne("ProjetoSara.Models.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("ProjetoSara.Models.Localizacao", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("ProjetoSara.Models.NivelAlerta", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("ProjetoSara.Models.Sensor", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("ProjetoSara.Models.StatusNotificacao", b =>
                {
                    b.Navigation("Notificacoes");
                });

            modelBuilder.Entity("ProjetoSara.Models.TipoSensor", b =>
                {
                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("ProjetoSara.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProjetoSara.Models.Usuario", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Notificacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
